schema = 3

[mod]
  [mod."github.com/coreos/go-semver"]
    version = "v0.3.1"
    hash = "sha256-ZZPTQW8xCqYk4vERTu/nBvCB9D01xO3XfnyFPb0nQG8="
  [mod."github.com/coreos/go-systemd/v22"]
    version = "v22.5.0"
    hash = "sha256-E2zXikbmIQImghstLUWuey1YgA0Folu3F+fi5k4hCxA="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."go.etcd.io/etcd/api/v3"]
    version = "v3.5.12"
    hash = "sha256-eCB6yQyTrGfkiN4R5uilRgyWhJNW77Q3v0F1e3pquf0="
  [mod."go.etcd.io/etcd/client/pkg/v3"]
    version = "v3.5.12"
    hash = "sha256-PF9BVfNZy6rXNR8aZ8a+vtYdG7ABRQKKUKdwFzC9lXA="
  [mod."go.etcd.io/etcd/client/v3"]
    version = "v3.5.12"
    hash = "sha256-OKbBOCRCJLpw+ebydL6U34vv8h3kA0m7lO4uCZXFkqk="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/net"]
    version = "v0.22.0"
    hash = "sha256-pcefO4noO9I6mATKBWF6shgIjZvFg0kDsV1Jo/NsFns="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240304212257-790db918fca8"
    hash = "sha256-CgxPwcl7SfF+BLzoP9ICHIHUyAN7sAFndTCn2NnIjQw="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240304212257-790db918fca8"
    hash = "sha256-V2CfmnTb92os4IGejBvk5mNaINarJQYqrG0fU/WrCbE="
  [mod."google.golang.org/grpc"]
    version = "v1.62.1"
    hash = "sha256-1su6X0YT7MUflrTJijbq1CiisADZHudEx5sJq01TEaE="
  [mod."google.golang.org/protobuf"]
    version = "v1.33.0"
    hash = "sha256-cWwQjtUwSIEkAlAadrlxK1PYZXTRrV4NKzt7xDpJgIU="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
